# For split keyboards:
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# 오른쪽 트랙볼 15도 기울어짐 보정용 커스텀 input processor.
CONFIG_CROSSES_INPUT_PROCESSOR_ROTATE=y
