# Uncomment the following line to enable OLED Displays
# CONFIG_ZMK_DISPLAY=y

# Report battery for both sides of the keyboard
CONFIG_BT_BAS=y

# Passkey off
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

# Windows battery notification workaround
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# Runtime input processor.
# 오른쪽 트랙볼의 -15도 각도 보정용.
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR=y
